services:
  backend-app:
    container_name: cnpj_app
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app
  db:
    container_name: cnpj_db
    image: postgres:14
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/postgresql.conf


volumes:
  postgres_data: