services:
  backend-app:
    container_name: cnpj_app
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      WORKER_ID: "0"
    volumes:
      - .:/app
