services:
  backend-app:
    build: .
    restart: unless-stopped
    ports:
      - "80:8000"
    networks:
      - CNPJ_net
    volumes:
      - .:/app
    env_file: .env

networks:
  CNPJ_net:
    driver: bridge