<<<<<<< HEAD
backend-app:
  build: .
  restart: unless-stopped
  ports:
    - "80:8000"
  networks:
    - ConexxoHubNet
  volumes:
    - .:/app
  deploy:
    mode: replicated
    replicas: 1
    restart_policy:
      condition: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-app.entrypoints=websecure"
      - "traefik.http.routers.backend-app.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.backend-app.rule=Host(`cnpjapi.conexxohub.com.br`)"
      - "traefik.http.services.backend-app.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend-app.service=backend-app"
=======
services:
  backend-app:
    image: brunolnetto1234/cnpj_api:latest
    build: .
    restart: unless-stopped
    ports:
      - "8000d:8000"
>>>>>>> 6950956 (refactor: rollback changes)
    env_file: .env
    

networks:
  ConexxoHubNet:
    external: true
    attachable: true

  volumes:
    - .:/app
