services:
  backend-app:
    image: brunolnetto1234/cnpj_api:latest
    build: .
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.webpage.rule=Host(`cnpjapi.conexxohub.com.br`)"
        - "traefik.http.routers.webpage.entrypoints=websecure"
        - "traefik.http.routers.webpage.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.webpage.loadbalancer.server.port=8081"
    restart: unless-stopped
    ports:
      - "8081:8000"
    env_file: .env
    volumes:
      - .:/app
