version: '3.3'

services:
  backend-app:
    image: josezago/cnpj-api
    networks:
      - ConexxoHubNet
    deploy:
      mode: replicated
      replicas: 5
      placement:
        constraints: []
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend-app.entrypoints=web"
        - "traefik.http.routers.backend-app.rule=Host(`cnpjapi.conexxohub.com.br`)"
        - "traefik.http.services.backend-app.loadbalancer.server.port=8000"
        - "traefik.http.routers.backend-app.service=backend-app"
      

networks:
  ConexxoHubNet:
    external: true

