services:
  backend:
    container_name: cnpj_app
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env.test
    volumes:
      - .:/app
  db:
    container_name: cnpj_db
    image: postgres:17
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/some_name/
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/some_name
      - ./pg_hba.conf:/var/lib/postgresql/data/some_name/pg_hba.conf


volumes:
  postgres_data: